INSERT INTO COUNTRIES (ID, NAME, TAX, RATE_CODE, FIXED_COST) VALUES ('1', 'Stany Zjednoczone Ameryki', '21', 'USD', '1000');
INSERT INTO COUNTRIES (ID, NAME, TAX, RATE_CODE, FIXED_COST) VALUES ('2', 'Wielka Brytania', '25', 'GBP', '600');
INSERT INTO COUNTRIES (ID, NAME, TAX, RATE_CODE, FIXED_COST) VALUES ('3', 'Niemcy', '20', 'EUR', '800');
INSERT INTO COUNTRIES (ID, NAME, TAX, RATE_CODE, FIXED_COST) VALUES ('4', 'Polska', '19', 'PLN', '1200');
INSERT INTO COUNTRIES (ID, NAME, TAX, RATE_CODE, FIXED_COST) VALUES ('5', 'Szwajcaria', '25', 'CHF', '700');
